### PR TITLE
chore: fix mispelling

### LINKED ISSUE #1286: chore:lint:ci enable misspell linter
Enable the misspell linter.

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/542bafac48806735b15164f5abf66cb7a1aa299f/.golangci.yaml#L40

Advice to implementors:
* try to cap your work around ~< 50 file changes
* in this case, a few smaller PRs is better than one big PR

Steps to tackle this:
- turn on linter locally by uncommenting
- fix issues

### PR DESCRIPTION
**Pull request by anhdle-sso**
### Change description

Fixes #1286

### Tests you have done

- [ x] Run `make ready-pr` to ensure this PR is ready for review.
- [ x] Perform necessary E2E testing for changed resources.

### CODE REVIEW

File: pkg/krmtotf/tftokrm.go [hunk 1]
```diff
@@ -435,7 +435,7 @@ func getValueFromState(state map[string]interface{}, key string) (string, bool)
 //
 // prevSpec is used for multiple purposes:
 //   - ensures the returned result has a similar order for objects in lists, reducing
-//     the percieved diff when applied.
+//     the `perceived diff when applied.
```
Comment (acpana) [inline pkg/krmtotf/tftokrm.go:438]:
```suggestion
//     the perceived diff when applied.
```

**Comment by acpana** [comment]
/lgtm
/approve

thanks for doing this 🥇 glad it wasn't too bad hehe
