### PR TITLE
Avoid fetching resource config for direct resources

### LINKED ISSUE #3830: Tag 1.129.2 breaks PrivilegedAccessManagerEntitlement reconciliation
### Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

We picked up and rolled out v1.129.2 into our clusters which broke PrivilegedAccessManagerEntitlement reconciliation. I understand this is not an "official" release yet but raising this issue in case this is something you were unaware of.

After the upgrade our root-reconciler logs show
```
"admission webhook "deny-immutable-field-updates.cnrm.cloud.google.com" denied the request: couldn't get ResourceConfig for kind PrivilegedAccessManagerEntitlement: error getting service mapping: no mapping with name 'privilegedaccessmanager.cnrm.cloud.google.com' found
```

https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3443 appears to remove some service mappings and do some reshuffling, which looks relevant.
 

### Additional Diagnostic Information

N/A

### Kubernetes Cluster Version

1.30.9-gke.1046000

### Config Connector Version

1.129.2

### Config Connector Mode

namespaced mode (default)

### Log Output

_No response_

### Steps to reproduce the issue

Set `cnrm.cloud.google.com/operator-version` to 1.129.2. on CRDs for `ConfigConnector` etc. 

### YAML snippets

```YAML

```

### PR DESCRIPTION
**Pull request by maqiuyujoyce**
### Change description

Fixes #3830

Added test case to ensure direct resources are always allowed by the immutable validator.

### Tests you have done

- [N/A] Run `make ready-pr` to ensure this PR is ready for review.
- [X] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Review by jingyih — COMMENTED** [review]
/lgtm

File: pkg/webhook/immutable_fields_validator.go [hunk 1]
```diff
@@ -290,15 +290,15 @@ func getQualifiedFieldName(prefix string, fieldName string) string {
 }
 
 func validateImmutableFieldsForTFBasedResource(obj, oldObj *unstructured.Unstructured, spec, oldSpec map[string]interface{}, smLoader *servicemappingloader.ServiceMappingLoader, tfResourceMap map[string]*tfschema.Resource) admission.Response {
+	isDirect := supportedgvks.IsDirectByGVK(obj.GroupVersionKind())
+	if isDirect && obj.GetKind() != "SQLInstance" {
```
Comment (yuwenma) [inline pkg/webhook/immutable_fields_validator.go:294]: Do we have test coverage to verify this change? I suggest we don't hard-code the kind in the webhook because there is no test coverage for the legacy logic here.

Comment (jasonvigil) [reply pkg/webhook/immutable_fields_validator.go:294]: I think it's ok to remove the special case for SQLInstance here. We can allow the field mutations, and report errors (if any) back from the GCP API.

Comment (yuwenma) [reply pkg/webhook/immutable_fields_validator.go:294]: Thanks for confirming, @jasonvigil ! Glad that we can eventually drop this hard-coded line. 

@maqiuyujoyce Could you remove the code and add a test coverage to verify the change fixes the reported issue?

**Comment by yuwenma** [comment]
Gentle ping on this PR @maqiuyujoyce

File: pkg/webhook/immutable_fields_validator.go (hunk 1 above)
Comment (maqiuyujoyce) [reply pkg/webhook/immutable_fields_validator.go]: Done.

**Review by jingyih — COMMENTED** [review]
/lgtm

**Review by yuwenma — COMMENTED** [review]
/approve
