### PR TITLE
fix(sql): default QueryPlansPerMinute and improve mock normalization

### LINKED ISSUE #6377: bug: CloudSQL settings.insightConfig.queryPlansPerMinute defaulting behavior
If user does not set  settings.insightConfig.queryPlansPerMinute. CloudSQL API will default the value to 5, which then cause constant reconcilation.

### PR DESCRIPTION
**Pull request by anhdle-sso**
### Description
This PR addresses an issue with `QueryPlansPerMinute` defaults in [SQLInstance] and improves the stability of mock data normalization for SQL instances.
**Changes:**
- **SQLInstance Defaults**: Updated [pkg/controller/direct/sql/sqlinstance_defaults.go] to explicitly set `Settings.InsightsConfig.QueryPlansPerMinute` to `5` (the GCP default) when unspecified in the KRM. This ensures consistent behavior for insights configuration.
- **Mock Normalization**: Enhanced [mockgcp/mocksql/normalize.go] to normalize IP addresses for types "PRIMARY" and "OUTGOING" (in addition to "PRIVATE"). This reduces golden file noise caused by dynamic IP values.
- **Testing**: Added a new test case `sqlinstance-insightsconfig-qpm-default` to verify the default handling of `QueryPlansPerMinute`.
    - Includes new real GCP HTTP logs and golden files.
    - Updated existing `_http.log` files to reflect the improved IP normalization.

Fixes #6377

#### Does this PR add something which needs to be 'release noted'?

```release-note

```

- [ ] Reviewer reviewed release note.

#### Additional documentation e.g., references, usage docs, etc.:

```docs

```

#### Intended Milestone

Please indicate the intended milestone. 
- [ ] Reviewer tagged PR with the actual milestone.

### Tests you have done

- [ ] Run `make ready-pr` to ensure this PR is ready for review.
- [ ] Perform necessary E2E testing for changed resources.

### CODE REVIEW

File: pkg/controller/direct/sql/sqlinstance_defaults.go [hunk 1]
```diff
@@ -66,6 +66,11 @@ func ApplySQLInstanceGCPDefaults(in *krm.SQLInstance, out *api.DatabaseInstance,
 		// Apply client side GCP default Edition is ENTERPRISE.
 		out.Settings.Edition = "ENTERPRISE"
 	}
+	if in.Spec.Settings.InsightsConfig != nil {
+		if in.Spec.Settings.InsightsConfig.QueryPlansPerMinute == nil {
+			out.Settings.InsightsConfig.QueryPlansPerMinute = 5
+		}
```
Comment (gemmahou) [inline pkg/controller/direct/sql/sqlinstance_defaults.go]: Ensure that `out.Settings.InsightsConfig` is initialized before accessing `QueryPlansPerMinute`. If the mapper did not create `InsightsConfig` (e.g., because all source fields were nil), this assignment will panic. Consider adding a nil check and initialization: `if out.Settings.InsightsConfig == nil { out.Settings.InsightsConfig = &api.InsightsConfig{} }`.

Comment (gemmahou) [inline pkg/controller/direct/sql/sqlinstance_defaults.go:78]: Agent: Avoid magic number `5`. Consider defining a constant `DefaultQueryPlansPerMinute = 5` for better readability and maintainability.

File: mockgcp/mocksql/normalize.go [hunk 2]
```diff
@@ -41,8 +41,13 @@ func (s *MockService) Previsit(event mockgcpregistry.Event, replacements mockgcp
 	}
 	if ok := event.ParseResponseInto(&sqlInstance); ok {
 		for _, ipAddress := range sqlInstance.IPAddresses {
```
Comment (gemmahou) [inline mockgcp/mocksql/normalize.go]: Good refactoring to use `switch` for handling multiple IP types.

File: mockgcp/mocksql/normalize.go [hunk 3]
```diff
@@ -41,8 +41,13 @@ func (s *MockService) Previsit(event mockgcpregistry.Event, replacements mockgcp
...
-			if ipAddress.Type == "PRIVATE" {
+			switch ipAddress.Type {
+			case "PRIVATE":
 				replacements.ReplaceStringValue(ipAddress.IPAddress, "10.1.2.3")
```
Comment (gemmahou) [inline mockgcp/mocksql/normalize.go]: Usage of magic IP `"10.10.10.10"`. Consider defining this as a constant, e.g., `MockPrimaryIP`, to make the test data expectations clearer.

File: mockgcp/mocksql/normalize.go [hunk 4]
```diff
@@ -41,8 +41,13 @@ func (s *MockService) Previsit(event mockgcpregistry.Event, replacements mockgcp
...
+			case "PRIMARY":
+				replacements.ReplaceStringValue(ipAddress.IPAddress, "10.10.10.10")
```
Comment (gemmahou) [inline mockgcp/mocksql/normalize.go]: Same here, consider using a constant for `"10.10.10.11"` (e.g., `MockOutgoingIP`).

File: pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/create.yaml [hunk 5]
```diff
@@ -0,0 +1,36 @@
+# Copyright 2024 Google LLC
```
Comment (gemmahou) [inline pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/create.yaml]: Agent: Copyright year is 2024. Please update to 2026.

File: pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/create.yaml [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+apiVersion: sql.cnrm.cloud.google.com/v1beta1
+kind: SQLInstance
+metadata:
```
Comment (gemmahou) [inline pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/create.yaml]: Using `${uniqueId}` is good practice for test isolation.

File: pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/update.yaml [hunk 7]
```diff
@@ -0,0 +1,37 @@
+# Copyright 2026 Google LLC
```
Comment (gemmahou) [inline pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/update.yaml]: Copyright year 2026 is correct here.

File: pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/_generated_object_sqlinstance-insightsconfig-qpm-default.golden.yaml [hunk 8]
```diff
@@ -0,0 +1,50 @@
...
+    cnrm-test: "true"
+  name: sqlinstance-insightsconfig-direct-${uniqueId}
+  namespace: ${uniqueId}
+spec:
+  databaseVersion: POSTGRES_15
+  region: us-central1
+  settings:
+    insightsConfig:
+      queryInsightsEnabled: true
+      queryPlansPerMinute: 10
```
Comment (gemmahou) [inline pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/_generated_object_sqlinstance-insightsconfig-qpm-default.golden.yaml]: `queryPlansPerMinute` is set to 10 here, which matches the `update.yaml`. This confirms the test flow correctly updates the value.

File: pkg/controller/direct/sql/sqlinstance_defaults.go [hunk 9]
```diff
@@ -66,6 +66,11 @@ func ApplySQLInstanceGCPDefaults(in *krm.SQLInstance, out *api.DatabaseInstance,
 		// Apply client side GCP default Edition is ENTERPRISE.
 		out.Settings.Edition = "ENTERPRISE"
 	}
+	if in.Spec.Settings.InsightsConfig != nil {
+		if in.Spec.Settings.InsightsConfig.QueryPlansPerMinute == nil {
```
Comment (gemmahou) [inline pkg/controller/direct/sql/sqlinstance_defaults.go]: This check `in.Spec.Settings.InsightsConfig != nil` correctly prevents defaults from being applied if the user hasn't enabled/configured `InsightsConfig` at all.

File: pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/_http.log [hunk 10]
```diff
@@ -0,0 +1,674 @@
...
+  "name": "sqlinstance-insightsconfig-direct-${uniqueId}",
+  "region": "us-central1",
+  "settings": {
+    "activationPolicy": "ALWAYS",
+    "availabilityType": "ZONAL",
+    "connectorEnforcement": "NOT_REQUIRED",
+    "dataDiskType": "PD_SSD",
+    "edition": "ENTERPRISE",
+    "insightsConfig": {
+      "queryInsightsEnabled": false,
```
Comment (gemmahou) [inline pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/_http.log]: Logs confirm `queryPlansPerMinute: 5` is sent in the CREATE request, verifying the default logic.

File: pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/_http.log [hunk 11]
```diff
@@ -0,0 +1,674 @@
...
+      "recordClientAddress": true
+    },
+    "ipConfiguration": {
+      "ipv4Enabled": true,
+      "sslMode": "ALLOW_UNENCRYPTED_AND_ENCRYPTED"
+    },
+    "kind": "sql#settings",
+    "locationPreference": {
+      "kind": "sql#locationPreference",
+      "zone": "us-central1-a"
```
Comment (gemmahou) [inline pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/_http.log]: Logs confirm `queryPlansPerMinute: 10` is sent in the UPDATE request.

File: pkg/controller/direct/sql/sqlinstance_defaults.go [hunk 12]
```diff
@@ -66,6 +66,11 @@ func ApplySQLInstanceGCPDefaults(in *krm.SQLInstance, out *api.DatabaseInstance,
...
+			out.Settings.InsightsConfig.QueryPlansPerMinute = 5
```
Comment (gemmahou) [inline pkg/controller/direct/sql/sqlinstance_defaults.go]: Gemma: I'm wondering the value default for `QueryPlansPerMinute` ONLY when `queryInsightsEnabled` is `true`? Let's make sure we also handle the case correctly when  `queryInsightsEnabled` is `false`.

File: pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/_http.log [hunk 13]
```diff
@@ -0,0 +1,674 @@
...
+  "region": "us-central1",
+  "settings": {
+    "activationPolicy": "ALWAYS",
+    "availabilityType": "ZONAL",
+    "connectorEnforcement": "NOT_REQUIRED",
+    "dataDiskType": "PD_SSD",
+    "edition": "ENTERPRISE",
+    "insightsConfig": {
+      "queryInsightsEnabled": false,
+      "queryPlansPerMinute": 5,
```
Comment (gemmahou) [inline pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/_http.log:48]: I want to double-check if `queryPlansPerMinute` is `5` even when `queryInsightsEnabled` is `false`. I'm afraid the additional value would cause issues when comparing with the actual resource.

Comment (anhdle-sso) [reply pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/_http.log:48]: I already have `"queryInsightsEnabled": false` in the test case

File: pkg/controller/direct/sql/sqlinstance_defaults.go (hunk 12 above)
Comment (anhdle-sso) [reply pkg/controller/direct/sql/sqlinstance_defaults.go]: The `create.yaml` has `queryInsightsEnabled` set to false

File: pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/create.yaml (hunk 5 above)
Comment (anhdle-sso) [reply pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-insightsconfig-qpm-default/create.yaml]: done

**Comment by yuwenma** [comment]
/approve
/lgtm

Just want to raise 2 potential concerns for future work:
1.  if the GCP changes the default, users would hit an unexpected "KCC not using default" problem. This causes the previous Enterprise and Maintenance version issue.
2. The #6377 problem only happens for update, but changing ApplySQLInstanceGCPDefaults would affect the "CREATION" as well (same user problem if GCP changes the default).

**Review by yuwenma — APPROVED** [review]
