### PR TITLE
fix: Move resolvers out of Adapter

### LINKED ISSUE #2621: Investigate presubmit samples test failures
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

The presubmit samples failed after PR#2583, and that blocks the open PRs.

The two failed tests are samples/regional-forwarding-rule-vpc-psc and samples/computeserviceattachment(flaky).

Checking the logs, the forwarding rule is a dependency of the service attachment, and the deletion of the forwarding rule is blocked because there is no network (the network was deleted before). It seems like we need to handle the deletion ordering in the direct controller. It's strange that the presubmit on the original PR passed. I had a temporary fix: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2614, but the two tests are still failing, so I think there's a deeper issue (deletion ordering, etc.).

### Additional Diagnostic Information

job: https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/10681623224/job/29605684721

### Kubernetes Cluster Version

N/A

### Config Connector Version

N/A

### Config Connector Mode

namespaced mode (default)

### Log Output

_No response_

### Steps to reproduce the issue

N/A

### YAML snippets

_No response_

### PR DESCRIPTION
**Pull request by gemmahou**
### Change description

Deleting a resource does not require resolving dependencies. However, if dependencies are deleted prior to the resource itself, it will prevent the deletion of that resource.

Therefore, we should move resolvers to their own function outside the Adapter. We can resolve them during the create and update only.

Fixes #2621 

### Tests you have done

- [x] Run `make ready-pr` to ensure this PR is ready for review.
- [x] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Comment by gemmahou** [comment]
The presubmit pause job failed, I think we need to increase the timeout of this job.

File: config/tests/samples/create/harness.go [hunk 1]
```diff
@@ -673,7 +673,7 @@ func MaybeSkip(t *testing.T, name string, resources []*unstructured.Unstructured
 			case schema.GroupKind{Group: "compute.cnrm.cloud.google.com", Kind: "ComputeNodeGroup"}:
 			case schema.GroupKind{Group: "compute.cnrm.cloud.google.com", Kind: "ComputeNodeTemplate"}:
 			case schema.GroupKind{Group: "compute.cnrm.cloud.google.com", Kind: "ComputeManagedSSLCertificate"}:
-			//case schema.GroupKind{Group: "compute.cnrm.cloud.google.com", Kind: "ComputeServiceAttachment"}:
```
Comment (yuwenma) [inline config/tests/samples/create/harness.go:676]: is this intended?

File: pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeserviceattachment/_http.log [hunk 2]
```diff
@@ -1187,6 +1187,86 @@ X-Content-Type-Options: nosniff
...
+  "network": "https://www.googleapis.com/compute/v1/projects/example-project-01/global/networks/${networkID}",
+  "networkTier": "PREMIUM",
+  "region": "https://www.googleapis.com/compute/v1/projects/example-project-01/regions/us-west1",
+  "selfLink": "https://www.googleapis.com/compute/v1/projects/example-project-01/regions/us-west1/forwardingRules/computeforwardingrule-${uniqueId}",
+  "subnetwork": "https://www.googleapis.com/compute/v1/projects/example-project-01/regions/us-west1/subnetworks/computesubnetwork-3-${uniqueId}"
+}
+
+---
+
+POST https://compute.googleapis.com/compute/v1/projects/example-project-01/regions/us-west1/forwardingRules/${forwardingRuleID}/setLabels
```
Comment (yuwenma) [inline pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeserviceattachment/_http.log:1211]: Do you know how the code change ends up with a new setLabels call? This looks weird

**Review by yuwenma — COMMENTED** [review]
/approve

2 questions: otherwise looks good

File: config/tests/samples/create/harness.go (hunk 1 above)
Comment (gemmahou) [reply config/tests/samples/create/harness.go:676]: Yes, we started noticing this deletion issue in a forwarding rule test with service attachment dependency, and it blocked presubmits. So, we disabled this mock service. #1069

I added it back here because the issue has been addressed in this PR, and the presubmits all passed now.

File: pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeserviceattachment/_http.log (hunk 2 above)
Comment (gemmahou) [reply pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeserviceattachment/_http.log:1211]: I reason is I disabled this test before #1069, so I haven't updated its log to reflect the recent code changes(the set labels behavior during creation). I can collect the realGCP w/TF log to verify this change in the log is intended.

File: pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeserviceattachment/_http.log [hunk 3]
```diff
@@ -1187,6 +1187,86 @@ X-Content-Type-Options: nosniff
 X-Frame-Options: SAMEORIGIN
 X-Xss-Protection: 0
 
+{
+  "IPProtocol": "TCP",
```
Comment (yuwenma) [inline pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeserviceattachment/_http.log:1191]: ipProtocal?

**Review by yuwenma — COMMENTED** [review]
/lgtm
/approve

**Review by yuwenma — COMMENTED** [review]
/lgtm

**Comment by gemmahou** [comment]
I've created an issue to address this, as it seems to be a bug affecting several other direct controllers: https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/5620
